# Generated by Django 5.1.4 on 2024-12-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_submodule_order_video_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submodule',
            name='order',
        ),
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
        migrations.AlterField(
            model_name='submodule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
