# Generated by Django 5.1.4 on 2025-01-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_submodule_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='wistia_id',
            field=models.CharField(default=32, help_text="The Wistia media ID (e.g., 'nheca4ikpw')", max_length=100),
            preserve_default=False,
        ),
    ]
