# Generated by Django 5.1.4 on 2025-01-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_video_wistia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(help_text="The Wistia media ID (e.g., 'nheca4ikpw')", max_length=100),
        ),
    ]
